CREATE TABLE snap_locations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Store_Name TEXT NOT NULL,
    address TEXT,
    Address_Line__2 TEXT,
    City TEXT,
    Zip5 INTEGER,
    Zip4 INTEGER,
    County TEXT,
    Longitude INTEGER,
    Latitude INTEGER
);